---
- name: Satellite Installer Playbook
  hosts: localhost
  become: true
  collections:
    - redhat.satellite_operations
    - redhat.satellite

  vars:
    # Satellite Information
    # sat_user: "satprodadmin"
    sat_user: "admin"
    sat_pass: "secret"
    sat_org: "my test"
    def_scenario: "satellite"

    # RHSM Credentials
    rhsm_username: ""
    rhsm_password: ""

    # Standard Values
    sat_version: "6.16"
    base_os: "rhel9"

    # Path to the manifest file to be used during the installation
    manifest_path: "manifest.zip"

  tasks:

      - name: Disabling and Stopping firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped

     - name: Copying the Manifest
      ansible.builtin.copy:
        src: manifest.zip
        dest: /root/manifest.zip

    - name: Subscription-manager clean
      ansible.builtin.command: subscription-manager clean

    - name: Register to RHSM
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        force_register: yes

    - name: Attach the Correct Entitlement
      ansible.builtin.shell: |
        pool_id=$(subscription-manager list --all --available --matches="MCT3718" | grep Pool | head -n1 | awk '{print $3}') && subscription-manager attach --pool $pool_id
    # and for good measure attache this one
    - name: Attach the correct entitlement
      ansible.builtin.shell: |
        pool_id=$(subscription-manager list --all --available --matches="RH00008" | grep Pool | head -n1 | awk '{print $3}') && subscription-manager attach --pool $pool_id

    - name: Disabling all the Repos
      community.general.rhsm_repository:
        name: '*'
        state: disabled

    - name: Enabling the Necessary Repos for Installing Satellite on RHEL9
      community.general.rhsm_repository:
        name: rhel-9-for-x86_64-baseos-rpms,rhel-9-for-x86_64-appstream-rpms,satellite-6.16-for-rhel-9-x86_64-rpms,satellite-maintenance-6.16-for-rhel-9-x86_64-rpms
        state: enabled
      when: sat_version == "6.16" and base_os == "rhel9"

    - name: Updating the Server
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Installing Satellite Package
      ansible.builtin.yum:
        name: satellite
        state: present

    - name: Removing Puppetlabs SSL Directory "/etc/puppetlabs/puppet/ssl/"
      ansible.builtin.file:
        path: /etc/puppetlabs/puppet/ssl/
        state: absent

    # Calling the installer
    - import_role:
        name: redhat.satellite_operations.installer
      vars:
        satellite_installer_scenario: "{{ def_scenario }}"
        satellite_installer_options:
          - '--foreman-initial-organization "{{ sat_org }}"'
          - '--foreman-initial-admin-password {{ sat_pass }}'
      when: sat_version == "6.16"

    # Importing the manifest
    - import_role:
        name: redhat.satellite.manifest
      vars:
        - satellite_organization: "{{ sat_org }}"
        - satellite_manifest_path: "/root/manifest.zip"
        - satellite_server_url: "https://{{ ansible_facts['nodename'] }}"
        - satellite_username: "{{ sat_user }}"
        - satellite_password: "{{ sat_pass }}"
      tags:
        - post

    # Refreshing the manifest
    - name: Refreshing the Manifest
      ansible.builtin.command: hammer -u "{{ sat_user }}" -p "{{ sat_pass }}" subscription refresh-manifest --organization "{{ sat_org }}"
      tags:
        - post

    - name: Setup LDAP
      redhat.satellite.auth_source_ldap:
        name: "Example LDAP"
        host: " "
        server_url: "https://{{ ansible_facts['nodename'] }}"
        organizations:
          - "{{ sat_org }}"
        username: "{{ sat_user }}"
        password: "{{ sat_pass }}"
        account: SATRedHATAPPID
        base_dn: DC=us,DC=,DC=com
        groups_base: DC=us,DC=,DC=com
        tls: true
        server_type: active_directory
        port: 636
        onthefly_register: true
        usergroup_sync: true
        attr_mail: mail
        attr_login: 
        attr_firstname: givenName
        attr_lastname: sn
        attr_photo: " "
        state: present
      tags:
        - ldap

    - name: "Enable Repositories for OS Updates and Patches"
      redhat.satellite.repository_set:
        username: "{{ sat_user }}"
        password: "{{ sat_pass }}"
        server_url: "https://{{ ansible_facts['nodename'] }}"
        organization: "{{ sat_org }}"
        state: enabled
        label: "{{ item.label }}"
        repositories: "{{ item.repositories | default(omit) }}"
        all_repositories: "{{ item.repositories is not defined }}"
      loop:
        - label: rhel-7-server-els-optional-rpms
        - label: rhel-7-server-els-rpms
        - label: rhel-7-server-satellite-maintenance-6-rpms
        - label: rhel-7-server-extras-rpms
        #
        - label: rhel-8-for-x86_64-baseos-rpms
          repositories: 
            - releasever: 8
        - label: rhel-8-for-x86_64-appstream-rpms
          repositories: 
            - releasever: 8
        - label: satellite-client-6-for-rhel-8-x86_64-rpms
        #
        - label: rhel-9-for-x86_64-baseos-rpms
          repositories: 
            - releasever: 9
        - label: rhel-9-for-x86_64-appstream-rpms
          repositories: 
            - releasever: 9
        - label: satellite-client-6-for-rhel-9-x86_64-rpms
      tags:
        - repos

    - name: "Repo Sync - Red Hat Enterprise Linux 8 for x86_64"
      redhat.satellite.repository_sync:
        username: "{{ sat_user }}"
        password: "{{ sat_pass }}"
        server_url: "https://{{ ansible_facts['nodename'] }}"
        organization: "{{ sat_org }}"
        product: "Red Hat Enterprise Linux for x86_64"
      tags:
        - repos

    - name: "Repo Sync - Red Hat Enterprise Linux 7 for x86_64"
      redhat.satellite.repository_sync:
        username: "{{ sat_user }}"
        password: "{{ sat_pass }}"
        server_url: "https://{{ ansible_facts['nodename'] }}"
        organization: "{{ sat_org }}"
        product: "Red Hat Enterprise Linux Server - Extended Life Cycle Support"
      tags:
        - repos

    - name: "Repo Sync - Red Hat Enterprise Linux 9 for x86_64"
      redhat.satellite.repository_sync:
        username: "{{ sat_user }}"
        password: "{{ sat_pass }}"
        server_url: "https://{{ ansible_facts['nodename'] }}"
        organization: "{{ sat_org }}"
        product: "Red Hat Enterprise Linux Server"
      tags:
        - repos

    # Creating a Sync Plan
    - import_role:
        name: redhat.satellite.sync_plans
      vars:
        satellite_organization: "{{ sat_org }}"
        satellite_server_url: "https://{{ ansible_facts['nodename'] }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_pass }}"
        satellite_sync_plans:
          - name: Daily Sync
            interval: daily
            sync_date: 2020-11-07 04:00:00 CDT
            products:
              - Red Hat Enterprise Linux for x86_64
              - Red Hat Enterprise Linux Server
              - Red Hat Enterprise Linux Server - Extended Life Cycle Support
      tags:
        - sync-plan

    # Creating the Lifecycle Environemnt
    - import_role:
        name: redhat.satellite.lifecycle_environments
      vars:
        satellite_organization: "{{ sat_org }}"
        satellite_server_url: "https://{{ ansible_facts['nodename'] }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_pass }}"
        satellite_lifecycle_environments:
          - name: "Previous"
            prior: "Library"
          - name: "Current"
            prior: "Previous"
      tags:
        - lifecycle

    # Creating the content view & composite content view
    - import_role:
        name: redhat.satellite.content_views
      vars:
        satellite_organization: "{{ sat_org }}"
        satellite_server_url: "https://{{ ansible_facts['nodename'] }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_pass }}"
        satellite_content_views:
          - name: RHEL7_base
            repositories:
              - name: Red Hat Enterprise Linux 7 Server - Extended Life Cycle Support - Optional RPMs x86_64
                product: 'Red Hat Enterprise Linux Server - Extended Life Cycle Support'
              - name: Red Hat Enterprise Linux 7 Server - Extended Life Cycle Support RPMs x86_64
                product: 'Red Hat Enterprise Linux Server - Extended Life Cycle Support'
          - name: RHEL7_composite
            auto_publish: true
            components:
              - content_view: RHEL7_base
                latest: true
      tags:
        - content-view

    - import_role:
        name: redhat.satellite.content_views
      vars:
        satellite_organization: "{{ sat_org }}"
        satellite_server_url: "https://{{ ansible_facts['nodename'] }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_pass }}"
        satellite_content_views:
          - name: RHEL8_base
            repositories:
              - name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8
                product: 'Red Hat Enterprise Linux for x86_64'
              - name: Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8
                product: 'Red Hat Enterprise Linux for x86_64'
              - name: Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs
                product: 'Red Hat Enterprise Linux for x86_64'
          - name: RHEL8_composite
            auto_publish: true
            components:
              - content_view: RHEL8_base
                latest: true
      tags:
        - content-view

    # Creating the content view & composite content view
    - import_role:
        name: redhat.satellite.content_views
      vars:
        satellite_organization: "{{ sat_org }}"
        satellite_server_url: "https://{{ ansible_facts['nodename'] }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_pass }}"
        satellite_content_views:
          - name: RHEL9_base
            repositories:
              - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9
                product: 'Red Hat Enterprise Linux for x86_64'
              - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9
                product: 'Red Hat Enterprise Linux for x86_64'
              - name: Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs
                product: 'Red Hat Enterprise Linux for x86_64'
          - name: RHEL9_composite
            auto_publish: true
            components:
              - content_view: RHEL9_base
                latest: true
      tags:
        - content-view

    # Publishing CV and CCV
    - import_role:
        name: redhat.satellite.content_view_publish
      vars:
        satellite_organization: "{{ sat_org }}"
        satellite_server_url: "https://{{ ansible_facts['nodename'] }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_pass }}"
        satellite_content_views:
          - RHEL7_base
          - RHEL8_base
          - RHEL9_base
      tags:
        - publish

    # Waiting for the sync task to finish, let's add a couple minutes
    - name: Pause for 3 minutes
      ansible.builtin.pause:
        minutes: 2

    - import_role:
        name: redhat.satellite.content_view_publish
      vars:
        satellite_organization: "{{ sat_org }}"
        satellite_server_url: "https://{{ ansible_facts['nodename'] }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_pass }}"
        satellite_content_views:
          - RHEL7_composite
          - RHEL8_composite
          - RHEL9_composite
      tags:
        - publish

    - name: "Ensure Content View for RHEL7 gets Promoted to Previous/Current"
      redhat.satellite.content_view_version:
        organization: "{{ sat_org }}"
        server_url: "https://{{ ansible_facts['nodename'] }}"
        username: "{{ sat_user }}"
        password: "{{ sat_pass }}"
        content_view: "RHEL7_composite"
        lifecycle_environments:
          - Previous
          - Current
      tags:
        - promote

    - name: "Ensure Content View for RHEL8 gets Promoted to Previous/Current"
      redhat.satellite.content_view_version:
        organization: "{{ sat_org }}"
        server_url: "https://{{ ansible_facts['nodename'] }}"
        username: "{{ sat_user }}"
        password: "{{ sat_pass }}"
        content_view: "RHEL8_composite"
        lifecycle_environments:
          - Previous
          - Current
      tags:
        - promote

    - name: "Ensure Content View for RHEL9 gets Promoted to Previous/Current"
      redhat.satellite.content_view_version:
        organization: "{{ sat_org }}"
        server_url: "https://{{ ansible_facts['nodename'] }}"
        username: "{{ sat_user }}"
        password: "{{ sat_pass }}"
        content_view: "RHEL9_composite"
        lifecycle_environments:
          - Previous
          - Current
      tags:
        - promote

    # Activation Key actions
    - import_role:
        name: redhat.satellite.activation_keys
      vars:
        satellite_organization: "{{ sat_org }}"
        satellite_server_url: "https://{{ ansible_facts['nodename'] }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_pass }}"
        satellite_activation_keys:
          - name: "ak_rhel7-prod"
            lifecycle_environment: "Current"
            content_view: "RHEL7_composite"
          - name: "ak_rhel8-prod"
            lifecycle_environment: "Current"
            content_view: "RHEL8_composite"
          - name: "ak_rhel9-prod"
            lifecycle_environment: "Current"
            content_view: "RHEL9_composite"
          - name: "ak_rhel7-non-prod"
            lifecycle_environment: "Current"
            content_view: "RHEL7_composite"
          - name: "ak_rhel8-non-prod"
            lifecycle_environment: "Current"
            content_view: "RHEL8_composite"
          - name: "ak_rhel9-non-prod"
            lifecycle_environment: "Current"
            content_view: "RHEL9_composite"
      tags:
        - ak      